### PR TITLE
add units to deviceMeta Calibration

### PR DESCRIPTION
**Pull request by kentquirk**
@jebeck

### CODE REVIEW

**Comment by jebeck** [comment]
Can we make this the PR where we add clarifying language to the `units` description in common fields please?

**Comment by kentquirk** [comment]
@jebeck -- added units text

**Comment by jebeck** [comment]
Tweaked units explanation. Have a look @kentquirk?

And I think it'd be good for @HowardLook and @brandonarbiter to sign off that this is clearer than the old documentation.

**Comment by jebeck** [comment]
Added warning about not using `inputUnits` as display units @kentquirk

**Comment by HowardLook** [comment]
Reviewed the new language in the documentation and I am comfortable with this. Thanks for checking.

**Pull request merged**
