### PR TITLE
add v1 activity data model

### PR DESCRIPTION
**Pull request by jebeck**
Replaces #15. Merging, as it was open way too long and we can continue to update as we see fit.

### CODE REVIEW

**Comment by kentquirk** [comment]
:(

I thought the reason we had not merged this was that we hadn't yet agreed that this was the right format or even that we should be creating these records. My recollection was that we had parked this for a future discussion.

**Comment by jebeck** [comment]
It wasn't even mergeable @kentquirk ...we can't park things indefinitely.

We aren't creating these records yet; they aren't set in stone. Still open for discussion, IMO.

I wouldn't be averse to a large **DRAFT** at the top or something. Would you like me to add that?

**Comment by jh-bate** [comment]
I want activity records. Yeah not perfect but its a start (i.e. all the
different intensity scales I feel are wasted ) but good enough to start
with.

**Comment by kentquirk** [comment]
Yes, please mark it as DRAFT.

**Pull request merged**
